--
-- Name: marketplace; Type: SCHEMA; Schema: -; Owner: tcero
--

CREATE SCHEMA IF NOT EXISTS marketplace;

ALTER SCHEMA marketplace OWNER TO tcero;

--
-- Name: productos; Type: TABLE; Schema: marketplace; Owner: tcero
--

CREATE TYPE marketplace.ciudad_enum AS ENUM ('Santiago','Viña del Mar','Antofagasta','Calama','La Serena','Concepción','Valdivia','Puerto Montt','Rancagua','Iquique','Temuco','Osorno','Copiapó','Arica','Talca','Punta Arenas','Chillán','Valparaíso','Curicó','Los Ángeles','Quilpué','Concon');
CREATE TYPE marketplace.portal_enum AS ENUM ('escortnorte','laplayaescort','relaxchile','planetaescort','estokada','chimbis','skokka','chaopescao','wenas.cl','sexosur');

CREATE TABLE marketplace.productos (
    id integer,
    text text,
    author character varying(125),
    tags text,
    job_id uuid,
    processed_at timestamp without time zone
);

CREATE TYPE marketplace.OAuthProvider AS ENUM ('google','internal');

CREATE TABLE marketplace.users (
    user_id uuid,
    nombre text,
    password text,
    roles text,
    avatar text,
    tokenProvider text,
    provider marketplace.OAuthProvider,
    email VARCHAR(255),
    ID_provider VARCHAR(255) NULL,
    confirmado BOOLEAN DEFAULT FALSE,
    PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS marketplace.modelos(
	id integer,
    id_job bigint,
	modelo varchar(125) UNIQUE,
	descripcion text,
	created_at timestamp,
	deleted_at timestamptz null,
	PRIMARY KEY(id,id_job)
);

CREATE TABLE IF NOT EXISTS marketplace.posts(
	id integer,
	id_modelos integer,
    id_job bigint,
	descripcion text,
	modelo varchar(125),
	fechaRegistro timestamp,
	created_at timestamp,
	likes integer,
	PRIMARY KEY (id,id_job)
);

CREATE TABLE IF NOT EXISTS marketplace.servicios (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE marketplace.ts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    id_job bigint NOT NULL,
    portal marketplace.portal_enum NOT NULL,
    idpagina TEXT NOT NULL,
    nombre TEXT,
    edad INT,
    ciudad marketplace.ciudad_enum,
    descripcion TEXT,
    deleted_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    scraped_at TIMESTAMP DEFAULT NOW(),

    descripcion_tsv tsvector GENERATED ALWAYS AS (
        to_tsvector('spanish', coalesce(descripcion, ''))
    ) STORED,

    UNIQUE (portal, idpagina)
);
CREATE TABLE marketplace.ts_servicios (
    ts_id UUID NOT NULL,
    servicio_id INT NOT NULL,
    tipo TEXT NOT NULL CHECK (tipo IN ('principal', 'adicional')), -- para distinguir servicios vs servicios_adicionales

    PRIMARY KEY (ts_id, servicio_id, tipo),
    FOREIGN KEY (ts_id) REFERENCES marketplace.ts(id) ON DELETE CASCADE,
    FOREIGN KEY (servicio_id) REFERENCES marketplace.servicios(id) ON DELETE RESTRICT
);

ALTER TABLE scrap.servicios_alias
ADD CONSTRAINT fk_servicios_alias_servicio
FOREIGN KEY (id_servicio)
REFERENCES marketplace.servicios(id);

CREATE INDEX idx_ts_servicios_ts_id ON marketplace.ts_servicios(ts_id);
CREATE INDEX idx_ts_servicios_servicio_id ON marketplace.ts_servicios(servicio_id);
CREATE INDEX idx_ts_servicios_tipo ON marketplace.ts_servicios(tipo);
CREATE INDEX idx_tss_servicio_ts ON marketplace.ts_servicios (servicio_id, ts_id);

CREATE INDEX idx_ts_descripcion_fts_gin 
ON marketplace.ts USING GIN (descripcion_tsv) 
WHERE deleted_at IS NULL;
CREATE INDEX idx_ts_portal 
ON marketplace.ts (portal) 
WHERE deleted_at IS NULL;

CREATE INDEX idx_ts_id_job 
ON marketplace.ts (id_job) 
WHERE deleted_at IS NULL;

CREATE INDEX idx_ts_ciudad 
ON marketplace.ts (ciudad) 
WHERE deleted_at IS NULL;

CREATE INDEX ON marketplace.modelos (deleted_at);
CREATE INDEX ON scrap.modelos (id_job, id);

 CREATE TABLE IF NOT EXISTS marketplace.recomendationsPosts (
    id SERIAL PRIMARY KEY,
    user_id uuid,
    post_id INTEGER,
    rating float4,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

 CREATE TABLE IF NOT EXISTS marketplace.recomendationsModels (
    id SERIAL PRIMARY KEY,
    user_id uuid,
    model_id INTEGER,
    rating float4,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

 CREATE TABLE IF NOT EXISTS marketplace.recomendationsts (
    id SERIAL PRIMARY KEY,
    user_id uuid,
    ts_id uuid,
    rating float4,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TYPE marketplace.relaciones AS ENUM ('CLICK');

CREATE TABLE marketplace.users_model(
    id serial, 
    id_user uuid, 
    model_nick varchar(255),
    magnitud integer,
    tipo marketplace.relaciones,
    PRIMARY KEY (id)
);

CREATE TABLE marketplace.outbox (
    id BIGSERIAL PRIMARY KEY,
    aggregate_type TEXT NOT NULL,
    aggregate_id TEXT NOT NULL,
    event_type TEXT NOT NULL,
    payload JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    processed BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_outbox_processed_created_at
ON marketplace.outbox (processed, created_at);

CREATE TABLE marketplace.posteos (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid,
  texto TEXT,
  menciones TEXT[],
  eliminado_en TIMESTAMPTZ,
  creado_en TIMESTAMPTZ DEFAULT NOW()
);
CREATE INDEX idx_posteos_menciones ON marketplace.posteos USING GIN (menciones);

CREATE TABLE marketplace.jwk_keys (
    kid        TEXT PRIMARY KEY,
    kty        TEXT NOT NULL,
    alg        TEXT NOT NULL,
    use        TEXT NOT NULL,
    private_jwk JSONB NOT NULL,
    public_jwk  JSONB NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP
);
