services:
  bff-service:
    image: tcero76/bff-service:873ade66e05ff28417561a373fe8f8910811fd6f
    build:
      dockerfile: ./bff-service/deploy/Dockerfile
      context: .
      target: ${PROFILE}
  front:
    image: tcero76/front:f812c8020d2163e3c2c12c44b515df2958285407
    build:
      dockerfile: deploy/Dockerfile
      context: ./front
      target: ${PROFILE}
  scrap-service:
    image: tcero76/scrap-service:b47455e824884168b6221a290e38b029d76f4454
    build:
      dockerfile: ./scrap-service/deploy/Dockerfile
      context: .
      target: ${PROFILE}
  beat-service:
    image: tcero76/beat-service:${TAG}
    build:
      dockerfile: beat-service/deploy/Dockerfile
      context: .
      target: ${PROFILE}
  rabbitmq-init:
    image: tcero76/rabbitmq-init:${TAG}
    build:
      dockerfile: Dockerfile
      context: infra/docker/config/rabbitmq/
  hydra:
    build:
      dockerfile: Dockerfile
      context: infra/docker/config/hydra/
      target: ${PROFILE}
  flyway:
    image: tcero76/flyway:668687e2b19faa67cf6356ff6e49c1bb9f06c1c6
    build:
      dockerfile: deploy/Dockerfile
      context: flyway/
      target: ${PROFILE}