services:
  bff-service:
    working_dir: /bff-service
    command: ["/app/main"]
    environment:
      - PORT=3000
      - POSTGRES_PORT_WRITE=${POSTGRES_PORT}
      - POSTGRES_PORT_READ=${POSTGRES_PORT}
      - HOST_EXTERNAL=${HOST_EXTERNAL}
      - REDIRECT_URL=${PROTOCOL_EXTERNAL}://${HOST_EXTERNAL}:${PORT_EXTERNAL}/bff/callback
      - HYDRA_ADMIN_URL=http://hydra:4445
      - HYDRA_PUBLIC_URL=http://hydra:4444
      - GOOGLE_OAUTH2_CLIENT_SECRET_FILE=/run/secrets/google_oauth2_client_secret
      - GOOGLE_OAUTH2_CLIENT_ID_FILE=/run/secrets/google_oauth2_client_id
      - CLIENT_ID_FILE=/run/secrets/client_id
      - CLIENT_SECRET_FILE=/run/secrets/client_secret
      - GOOGLE_OAUTH2_REDIRECT_URI=${GOOGLE_OAUTH2_REDIRECT_URI}
      - PROFILE=${PROFILE}
      - REDIS_HOST=${REDIS_HOST}
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT_WRITE}
      - POSTGRES_DB=${POSTGRES_DB}
      - MONITOREO=${MONITOREO}
    networks:
      - ${NETWORK_APPLICATION:-application}
    secrets:
      - google_oauth2_client_secret
      - google_oauth2_client_id
      - client_id
      - client_secret
      - postgres_password
    depends_on:
      - db
      - broker
      - hydra
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.middlewares.bff-strip.stripprefix.prefixes=/bff
        - traefik.http.routers.bff.rule=PathPrefix(`/bff`)
        - traefik.http.routers.bff.entrypoints=websecure
        - traefik.swarm.network=${NETWORK_APPLICATION:-application}
        # - traefik.http.routers.front.tls.certresolver=le
        - traefik.http.services.bff.loadbalancer.server.port=3000
        - traefik.http.routers.bff.middlewares=bff-strip
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-manager
      restart_policy:
        condition: on-failure
  front:
    working_dir: /app
    environment:
      - NEXT_PUBLIC_HOST=${PROTOCOL_EXTERNAL}://${HOST_EXTERNAL}
      - NEXT_PUBLIC_WS=${PROTOCOL_WS_EXTERNAL}://${HOST_EXTERNAL}
      - NEXT_PUBLIC_HYDRA=${PROTOCOL_EXTERNAL}://auth.${HOST_EXTERNAL}
      - NEXT_PUBLIC_CLIENT_ID=${CLIENT_ID}
      - NEXT_PUBLIC_MOCK=${VITE_MOCK}
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${GOOGLE_OAUTH2_CLIENT_ID}
      - NEXT_PUBLIC_HOME_PAGE_PATH=${HOME_PAGE_PATH}
    networks:
      - ${NETWORK_APPLICATION:-application}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.front.rule=Host(`${HOST_EXTERNAL}`)
        - traefik.swarm.network=${NETWORK_APPLICATION:-application}
        - traefik.http.routers.front.entrypoints=websecure
        - traefik.http.routers.front.tls=true
        # - traefik.http.routers.front.tls.certresolver=le
        - traefik.http.services.front.loadbalancer.server.port=3000
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-manager
      restart_policy:
        condition: on-failure
  scrap-service:
    working_dir: /app/scrap-service
    command: [ "celery", "-A", "main", "worker", "--loglevel=debug"]
    secrets:
      - postgres_password
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT_WRITE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - BROKER=${BROKER}
      - PORT=8000
      - TOTAL_POSTS=${TOTAL_POSTS}
      - CMD_SCRAPY_START_QUEUE=${CMD_SCRAPY_START_QUEUE}
      - CMD_SCRAPY_START_EXCHANGE=${CMD_SCRAPY_START_EXCHANGE}
    networks:
      - ${NETWORK_APPLICATION:-application}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-manager
      restart_policy:
        condition: on-failure
  beat-service:
    working_dir: /app/beat-service
    user: app
    entrypoint: [ "celery", "-A", "main", "beat", "--schedule=/tmp/celery/celerybeat-schedule","--loglevel=debug"]
    environment:
      - BROKER=${BROKER}
      - CRON_HOUR=${CRON_HOUR}
      - CRON_MINUTE=${CRON_MINUTE}
      - RECOMENDER_QUEUE=${RECOMENDER_QUEUE}
      - SCRAPY_QUEUE=${SCRAPY_QUEUE}
    networks:
      - ${NETWORK_APPLICATION:-application}
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-manager
      restart_policy:
        condition: on-failure