services:
  traefik:
    image: traefik:${TRAEFIK_VERSION}
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"

      - "--log.level=DEBUG"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.rtmp.address=:1935"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
#      - "--certificatesresolvers.le.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
      # - "--certificatesresolvers.le.acme.email=admin@${HOST_EXTERNAL}"
      # - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      # - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"

      - "--providers.swarm=true"
      - "--providers.swarm.endpoint=unix:///var/run/docker.sock"
      - "--providers.swarm.exposedbydefault=false"
    configs:
      - source: traefik_tls
        target: /etc/traefik/dynamic/tls.yml
    secrets:
     - traefik_server_crt
     - traefik_server_key
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - ${NETWORK_APPLICATION:-application}
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.rule=Host(`traefik.${HOST_EXTERNAL}`)
        - traefik.http.routers.traefik.entrypoints=websecure
        # - traefik.http.routers.traefik.tls.certresolver=le
        - traefik.http.routers.traefik.tls=true
        - traefik.http.routers.traefik.service=api@internal
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == swarm-manager
      restart_policy:
        condition: on-failure