services:
  hydra:
    image: oryd/hydra:${HYDRA_VERSION}
    container_name: hydra
    tty: true
    stdin_open: true
    ports:
      - "4444:4444"
      - "4445:4445"
    profiles:
      - hydra
    entrypoint: ["hydra", "serve", "all"]
    environment:
      - DSN=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:5432/${POSTGRES_DB}?sslmode=disable&options=-c%20search_path%3Dhydra
      - URLS_SELF_ISSUER=${PROTOCOL_EXTERNAL}://auth.${HOST_EXTERNAL}
      - URLS_LOGIN=${PROTOCOL_EXTERNAL}://${HOST_EXTERNAL}/${HOME_PAGE_PATH}/login 
      - URLS_CONSENT=${PROTOCOL_EXTERNAL}://${HOST_EXTERNAL}/bff/consent
      - URLS_ERROR=${PROTOCOL_EXTERNAL}://${HOST_EXTERNAL}/error
      - SECRETS_SYSTEM=${HYDRA_SECRET}
      - TTL_ACCESS_TOKEN=1000m
      - TTL_REFRESH_TOKEN=720h
    labels:
      - traefik.enable=true
      - traefik.http.routers.hydra.rule=Host(`auth.${HOST_EXTERNAL}`)
      - traefik.http.routers.hydra.entrypoints=websecure
      - traefik.http.routers.hydra.tls=true
      - traefik.http.services.hydra.loadbalancer.server.port=4444
    depends_on:
     - db
    networks:
      - ${NETWORK_APPLICATION:-application}