services:
  bff-service:
    image: tcero76/demo-bff-service:dev
    build:
      dockerfile: ./bff-service/deploy/Dockerfile
      context: .
      target: ${PROFILE}
  front:
    image: tcero76/demo-front:dev
    build:
      dockerfile: deploy/Dockerfile
      context: ./front
      target: ${PROFILE}
      args:
        VITE_HOST: "${PROTOCOL_EXTERNAL}://${HOST_EXTERNAL}:${PORT_EXTERNAL}"
        VITE_WS: "ws://${HOST_EXTERNAL}:${PORT_EXTERNAL}"
        VITE_CLIENT_ID: "${CLIENT_ID}"
        VITE_MOCK: ${VITE_MOCK}
  scrap-service:
    image: tcero76/demo-scrap-service:dev
    build:
      dockerfile: ./scrap-service/deploy/Dockerfile
      context: .
      target: ${PROFILE}
  beat-service:
    image: tcero76/demo-beat-service:dev
    build:
      dockerfile: beat-service/deploy/Dockerfile
      context: .
      target: ${PROFILE}
  e2e:
    image: tcero76/demo-e2e:dev
    build:
      dockerfile: deploy/Dockerfile
      context: ./e2e
      target: ${PROFILE}
    command: tail -f /dev/null