services:
  e2e:
    container_name: e2e
    working_dir: /e2e
    extra_hosts:
      - "${HOST_EXTERNAL}:172.30.0.10"
    environment:
      - URL_EXTERNAL=${PROTOCOL_EXTERNAL}://${HOST_EXTERNAL}
    profiles: 
      - e2e
    volumes:
      - ./e2e:/e2e
    networks:
      - application
      - proxy
    ports:
      - "5900:5900"
    depends_on:
      - front
      - bff-service
    entrypoint: ["/entrypoint.sh"]
    command: tail -f /dev/null
