name: deploy

on:
  # pull_request:
  #   branches:
  #     - main
  # push:
  #   branches:
  #     - main
  #   tags:
  #     - "v*.*.*"
  workflow_dispatch:
    inputs:
      run_job:
        description: "Job a ejecutar"
        required: true
        default: "all"
jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-22.04
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      TF_VAR_ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0
          terraform_wrapper: false
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve
        env:
          DO_SPACES_KEY: ${{ secrets.DO_SPACES_KEY }}
          DO_SPACES_SECRET: ${{ secrets.DO_SPACES_SECRET }}
        
      - name: Get Swarm Manager IP
        working-directory: terraform
        id: get_ip
        run: |
          set -euo pipefail
          manager_ip=$(terraform output -raw manager_public_ip)
          curl -u "${{ secrets.DDNS_USERNAME }}:${{ secrets.DDNS_PASSWORD }}" \
            "https://dynupdate.no-ip.com/nic/update?hostname=marketdemo.ddns.net&myip=$manager_ip"

  build_all:
    needs: [terraform]
    strategy:
      max-parallel: 1
      matrix:
        include:
          - service: front
            tag: push-front
            dir: front
            pattern: front
            image: tcero76/front
            prefix: FRONT

          - service: bff-service
            tag: push-bff
            dir: bff-service
            pattern: (bff-service|postgres|redis|rabbitmq|config)
            image: tcero76/bff-service
            prefix: BFF

          - service: scrap-service
            tag: push-scrap
            dir: scrap-service
            pattern: (scrap-service|rabbitmq)
            image: tcero76/scrap-service
            prefix: SCRAP

          - service: flyway
            tag: push-flyway
            dir: flyway
            pattern: flyway
            image: tcero76/flyway
            prefix: FLYWAY
    name: Build ${{ matrix.service }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: detecta cambios
        run: |
          git fetch --tags --force

          if git rev-parse "${{ matrix.tag }}" >/dev/null 2>&1; then
            LAST_PUSH=$(git rev-parse "${{ matrix.tag }}")
            echo "Último push: $LAST_PUSH"
            CHANGED_FILES=$(git diff --name-only "$LAST_PUSH" HEAD)
          else
            echo "Tag ${{ matrix.tag }} no existe. Primer build."
            CHANGED_FILES=$(git ls-files)
          fi

          if echo "$CHANGED_FILES" | grep -qE "^${{ matrix.pattern }}/"; then
            echo "${{ matrix.prefix }}_CHANGED=true" >> "$GITHUB_ENV"
          else
            echo "${{ matrix.prefix }}_CHANGED=false" >> "$GITHUB_ENV"
          fi

          echo "${{ matrix.prefix }}_BUILD=SKIPPED" >> "$GITHUB_ENV"

          echo "Pattern: ^${{ matrix.pattern }}/"
          echo "Changed files:"
          echo "$CHANGED_FILES"

      - name: Build ${{ matrix.service }}
        if: env[format('{0}_CHANGED', matrix.prefix)] == 'true'
        env:
          HOST_EXTERNAL: ${{ vars.MANAGER_IP }}
          VITE_MOCK: ${{ vars.VITE_MOCK }}
          GOOGLE_OAUTH2_CLIENT_ID: ${{ secrets.GOOGLE_OAUTH2_CLIENT_ID }}
        run: |
          BUILD_ENV_KEYS=(
            PROTOCOL_EXTERNAL
            HOST_EXTERNAL
            PROTOCOL_WS_EXTERNAL
            CLIENT_ID
            VITE_MOCK
            GOOGLE_OAUTH2_CLIENT_ID
            HOME_PAGE_PATH
          )
          PATTERN=$(IFS='|'; echo "${BUILD_ENV_KEYS[*]}")
          set -a
            source <(grep -E "^(${PATTERN})=" infra/.env)
          set +a
          sed -i "s|image: ${{ matrix.image }}:.*|image: ${{ matrix.image }}:${{ github.sha }}|g" infra/docker/prod/imagenes.yml
          if docker compose --project-directory "$PWD" --project-name marketplace -f infra/docker/prod/imagenes.yml build "${{ matrix.service }}" --push; then
            if docker manifest inspect "${{ matrix.image }}:${{ github.sha }}" >/dev/null 2>&1; then
              git fetch --tags --force
              git tag -f "${{ matrix.tag }}" "$GITHUB_SHA"
              if git push origin "refs/tags/${{ matrix.tag }}" --force; then
                STATUS="SUCCESS"
              else
                STATUS="TAG_PUSH_ERROR"
              fi
            else
              STATUS="VERIFY_FAILED"
            fi
          else
            STATUS="FAILED"
          fi
          echo "${{ matrix.service }}_BUILD=$STATUS" >> "$GITHUB_ENV"
          echo "Resultado build $SERVICE: $STATUS"

  deploy:
    name: Update environment variables on Manager
    runs-on: ubuntu-22.04
    needs: [build_all]
    permissions:
      contents: write
    if: ${{ always() }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Copiar .env base
        run: |
          scp infra/.env root@${{ vars.MANAGER_IP }}:/root/.env

      - name: Configurar variables de producción
        run: |
          ssh root@${{ vars.MANAGER_IP }} "
            cat >> /root/.env <<EOF
            PROFILE=${{ vars.PROFILE }}
            HOST_EXTERNAL=${{ vars.MANAGER_IP }}
            VITE_MOCK=${{ vars.VITE_MOCK }}
            PORT_EXTERNAL=${{ vars.PORT_EXTERNAL }}
            NETWORK_APPLICATION=${{ vars.NETWORK_APPLICATION }}
            TAG=${{ vars.TAG }}
            MONITOREO=${{ vars.MONITOREO }}
            EOF
          "
      - name: Crear config de Redis en Docker Swarm
        continue-on-error: true
        run: |
          ssh root@${{ vars.MANAGER_IP }} '
            bash /root/deploy-config.sh redis_config
          ' < infra/docker/config/redis/redis.conf
          ssh root@${{ vars.MANAGER_IP }} '
            bash /root/deploy-config.sh hydra_entrypoint
          ' < infra/docker/config/hydra/entrypoint.sh
          ssh root@${{ vars.MANAGER_IP }} '
            bash /root/deploy-config.sh traefik_tls
          ' < infra/docker/config/traefik/dynamic/tls_prod.yml
      - name: Crear secrets en Docker Swarm
        continue-on-error: true
        run: |
          ssh root@${{ vars.MANAGER_IP }} '
            bash /root/deploy-secret.sh postgres_password
          ' < <(printf "%s" "${{ secrets.POSTGRES_PASSWORD }}")
          ssh root@${{ vars.MANAGER_IP }} '
            bash /root/deploy-secret.sh client_id
          ' < <(printf "%s" "${{ secrets.CLIENT_ID }}")
          ssh root@${{ vars.MANAGER_IP }} '
            bash /root/deploy-secret.sh google_oauth2_client_id
          ' < <(printf "%s" "${{ secrets.GOOGLE_OAUTH2_CLIENT_ID }}")
          ssh root@${{ vars.MANAGER_IP }} '
            bash /root/deploy-secret.sh hydra_secret
          ' < <(printf "%s" "${{ secrets.HYDRA_SECRET }}")
          ssh root@${{ vars.MANAGER_IP }} '
            bash /root/deploy-secret.sh client_secret
          ' < <(printf "%s" "${{ secrets.CLIENT_SECRET }}")
          ssh root@${{ vars.MANAGER_IP }} '
            bash /root/deploy-secret.sh google_oauth2_client_secret
          ' < <(printf "%s" "${{ secrets.GOOGLE_OAUTH2_CLIENT_SECRET }}")
          ssh root@${{ vars.MANAGER_IP }} '
            bash /root/deploy-secret.sh traefik_server_crt
          ' < <(printf "%s" "${{ secrets.TRAEFIK_SERVER_CRT }}")
          ssh root@${{ vars.MANAGER_IP }} '
            bash /root/deploy-secret.sh traefik_server_key
          ' < <(printf "%s" "${{ secrets.TRAEFIK_SERVER_KEY }}")
        shell: bash

      - name: Generate image tags
        run: |
          git fetch --tags --force

          FRONT_SHA=$(git rev-parse push-front)
          BFF_SHA=$(git rev-parse push-bff)
          SCRAP_SHA=$(git rev-parse push-scrap)
          FLYWAY_SHA=$(git rev-parse push-flyway)
          cp infra/docker/prod/imagenes.yml infra/docker/prod/imagenes.generated.yml
          sed -i \
            -e "s|image: tcero76/front:.*|image: tcero76/front:${FRONT_SHA}|g" \
            -e "s|image: tcero76/bff-service:.*|image: tcero76/bff-service:${BFF_SHA}|g" \
            -e "s|image: tcero76/scrap-service:.*|image: tcero76/scrap-service:${SCRAP_SHA}|g" \
            -e "s|image: tcero76/flyway:.*|image: tcero76/flyway:${FLYWAY_SHA}|g" \
            infra/docker/prod/imagenes.generated.yml
          echo "===== imagenes.generated.yml ====="
          cat infra/docker/prod/imagenes.generated.yml

      - name: Copy docker-compose.yml to manager
        run: |
          git fetch origin
          git reset --hard ${{ github.sha }}
          ssh -o StrictHostKeyChecking=no root@${{ vars.MANAGER_IP }} "
            mkdir -p docker
          "
          scp -o StrictHostKeyChecking=no infra/docker/prod/* \
            root@${{ vars.MANAGER_IP }}:/root/docker/
          
          scp -o StrictHostKeyChecking=no \
            infra/docker/prod/imagenes.generated.yml \
            root@${{ vars.MANAGER_IP }}:/root/docker/imagenes.yml


      - name: excecute deploy
        run: ssh -o StrictHostKeyChecking=no root@${{ vars.MANAGER_IP }} "
            /root/deploy_stack.sh
          "
          echo "Desplegado"
      - name: Mark deployed commit
        run: |
          git tag -f deploy-prod HEAD
          git push origin deploy-prod --force

  report:
    name: Reporte Variables
    runs-on: ubuntu-22.04
    needs: [deploy]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Debug git build
        run: scripts/workflow/report.sh
