name: Unit Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run unit tests
        run: |
          docker compose \
            --env-file infra/test.env \
            --project-directory ${PWD} \
            --project-name marketplace \
            run --rm --no-deps bff-service \
            go test ./... -race