name: test-unit
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      run_job:
        description: "test-unit"
        required: true
        default: "all"
jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run unit tests
        run: |
          docker compose \
            --env-file infra/test.env \
            --project-directory ${PWD} \
            --project-name marketplace \
            run --rm --no-deps bff-service \
            go test ./controller ./config/ -race

  component-tests:
    name: Component Tests
    runs-on: ubuntu-latest
    env:
      ENVIRONMENTS: infra/test.env
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: mkdir volumes
        run: |
          mkdir -p /home/runner/work/marketplace/marketplace/infra/volumes/{timescaleDB/data,rabbitmq/data,redis/data,grafana/data,prometheus/data}
      - name: Set up test environment
        run: |
          docker compose \
            -f infra/docker/test/imagenes.yml \
            -f infra/docker/test/services.yml \
            -f infra/docker/test/common.yml \
            -f infra/docker/test/test.yml \
            -f infra/docker/test/hydra.yml \
            -f infra/docker/test/redis.yml \
            -f infra/docker/test/postgres.yml \
            --env-file infra/test.env \
            --project-directory ${PWD} \
            --project-name marketplace \
            up bff-service db cache hydra front -d
      - name: Run database migrations
        run: |
          set -a
          source "${ENVIRONMENTS}"
          set +a
          docker run --env-file ${ENVIRONMENTS} --network ${NETWORK_APPLICATION} --rm -v ./flyway/sql:/flyway/sql flyway/flyway:latest-alpine \
            -url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB} \
            -user=${POSTGRES_USER} \
            -password=${POSTGRES_PASSWORD} \
            -schemas=marketplace,scrap,hydra,marketplacedemo,chat,extension \
            -cleanDisabled=false \
            -locations=filesystem:/flyway/sql/migration,filesystem:/flyway/sql/seed \
            -placeholders.URL_EXTERNAL=${URL_EXTERNAL} \
            migrate
      - name: Run integration tests
        run: |
          docker compose \
            -f infra/docker/test/imagenes.yml \
            -f infra/docker/test/services.yml \
            -f infra/docker/test/common.yml \
            -f infra/docker/test/test.yml \
            -f infra/docker/test/hydra.yml \
            -f infra/docker/test/redis.yml \
            -f infra/docker/test/postgres.yml \
            --env-file infra/test.env \
            --project-directory ${PWD} \
            --project-name marketplace \
            run --rm --no-deps bff-service \
            go test ./integration -race
      - name: Run frontend component tests
        run: |
          set -a
          source "${ENVIRONMENTS}"
          set +a
          docker compose \
            --env-file infra/test.env \
            --project-directory ${PWD} \
            --project-name marketplace \
            run --rm --no-deps front \
            npm run test -- --run
      - name: Stop test environment
        if: always()
        run: |
          docker compose \
            --env-file infra/test.env \
            --project-directory ${PWD} \
            --project-name marketplace \
            down -v